# Generated by Django 5.0.1 on 2024-01-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
