# Generated by Django 5.0.1 on 2024-01-06 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
